# Generated by Django 3.1.5 on 2021-09-28 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPostPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=500)),
                ('is_default_picture', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_name_of_the_specificSpecification', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carAd.type')),
            ],
        ),
        migrations.CreateModel(
            name='CarPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name=2021)),
                ('price', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.model')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carposts', to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(to='carAd.CarPostPicture')),
                ('specifications', models.ManyToManyField(blank=True, to='carAd.Specification')),
            ],
        ),
    ]
